### ISSUE TITLE
Use Okhttp instead of HTTPUrlConnection

### ISSUE THREAD

**Issue by aegis123** [piwik/piwik-sdk-android#110]
A thing that bugged me was the try catch I needed when instantiating the tracker for a URL that I know to be good since I own the server. Then I started to refactor that in the end I ended up with a replacing HTTPUrlConnection with [Okhttp](http://square.github.io/okhttp/). Would you be interested in something like that.

**Comment by d4rken** [comment]
Since Android 4.4 HttpUrlConnection uses OkHttp internally already so I don't think there is a performance gain or footprint reduction. I think the piwik library would grow quite a bit due to the extra inclusion of OkHttp? Would there be any other benefits?

We could turn the exception into a runtime exception such that try catch is no longer necessary. It somewhat makes sense too because the Tracker URL is usually hardcoded and there is no way to sensibly recover from an MalformedURLException at that point.
