### ISSUE TITLE
2.0 Release?

### ISSUE THREAD

**Issue by d4rken** [piwik/piwik-sdk-android#154]
What's left to do?

- [x] #150
- [x] #97 
- [x] Check testing coverage and test saneness
- [x] Integrate 2.0 into a few more projects to spot usage issues?

I've deployed the 2.0 branch in my app to production and spotted no crash or anomalies in stats.

@eldk Any report on how it works for you?

**Comment by d4rken** [comment]
Updated the README and the wiki, so that part is ready for 2.0.

Had one more thought. Need to change the `Tracker` init to use a `TrackerConfig` so we can extend this without breaking the API in the future.

In anycase there doesn't seem to much activity... Did anyone do anymore testing or code review? 

I'll do one more app integration, go on holiday and when I'm back, if there is no opposition, release it?

**Comment by dotsbb** [comment]
I'm not testing 2.0 branch anymore.

> If there is no opposition, release it?

Sure thing

**Comment by d4rken** [comment]
I merged and released it.

**Comment by d4rken** [comment]
Maybe someone can fluff up the release notes? Link to tickets that were closed?

**Comment by mattab** [comment]
:tada:  Well done @d4rken  :tada: 

FYI using our Github Changelog Generator tool here is the generated changelog of closed issues since July 26th 2016:

piwik/piwik-sdk-android
#16 Offline mode missing [by @d4rken, @n8fr8]
#110 Use Okhttp instead of HTTPUrlConnection [by @d4rken]
#116 Unable to connect local piwik
#117 Problems tracking pages and visitors
#118 "Typo" in readme.md [by @eldk, @d4rken]
#119 API 10 - https PIWIK server - Could not validate certificate signature -
#120 Update dev branch with last commits from 138f8de [by @eldk, @dotsbb]
#121 Update dev branch with master [by @dotsbb, @d4rken]
#122 Why is minSDK to API 10 and not API 9 ?
#123 Gzipped dispatched json [by @eldk, @dotsbb]
#124 Update project to latest tool versions and API targets [by @d4rken]
#125 Add unit test for gzip setting [by @d4rken]
#126 Fixed javadoc issues (Java8 specs) [by @d4rken]
#127 Fixed a few lints [by @d4rken]
#128 UncaughtExceptionHandler fix [by @d4rken]
#129 Updated tools and libs [by @d4rken]
#130 Addresses #110. [by @d4rken]
#131 GZIP setting unit test [by @d4rken]
#132 Update doc : gzipped json dispatch [by @eldk, @dotsbb]
#133 No tracking
#134 Handle search events [by @d4rken]
#135 Added site-search to TrackHelper. [by @d4rken]
#136 Offline mode [by @d4rken]
#137 i get Value not defined in Custom Dimension
#138 Custom variable value in table overwrites when a new event is logged.
#139 FYI: Piwik Tracking API now allows data up to 24 hours in the past [by @eldk, @d4rken, @dotsbb]
#140 compile source for local maven repository
#141 Updated javadocs. [by @d4rken, @dotsbb]
#142 Improved bintray upload script. [by @d4rken]
#143 Up version on dev to v1.1.0 for the next release. [by @d4rken]
#144 Trying to fix travis. [by @d4rken]
#145 Add options for different dispatching modes. [by @d4rken]
#146 Updated javadocs. [by @d4rken]
#148 Architecture overhaul (SDK 2.0) [by @d4rken]
#151 Material design side menu
#155 2.0 Improvements [by @d4rken]
#156 Offline cache bug fixes [by @d4rken]
#157 Introducing `TrackerConfig` [by @d4rken]
#158 Allow custom identifiers when tracking downloads. [by @d4rken]
#159 2.0 [by @d4rken]
#160 2.0 Release [by @d4rken]
