### ISSUE TITLE
TrackerHelp.BaseEvent build method returns null

### ISSUE THREAD

**Issue by aegis123** [piwik/piwik-sdk-android#163]
When using the `TrackerHelper` to build Events the build method is annotated with `@Nullable`. This is a bit weird since you are using a the builder pattern to create null objects which should not be possible.

The proper way would be to throw an exception at either the setter or in the build method to notify the developer he is creating build an object with an inconsistent state. Also Proper usages of `@NonNull` and `@Nullable` annotations in the arguments can help the developer with supplying the proper value to the method.

**Comment by d4rken** [comment]
Something like #164 ?

The idea behind requiring null checks was that if the developer null checks these events, there would be less of a chance that unexpected tracking input crashes the app.

I agree with you though that this is counter intuitive to the builder pattern.

I'm not sure yet whether checking within the setters/constructors or in the `build()` call is the right move. Within `build()` would give the advantage that later changes to the methods wouldn't require extra checks because it still all goes through `build()`. Though one could also argue that it's better to fail early...

`Nullable` and `NonNull` annotation can still be improved in code, feel free to send a PR. Generally we should assume that a method argument/returnval is `NonNull` by default and otherwise annotate it (annotating everything with `NonNull` is a lot of spammy boilerplate).

**Comment by d4rken** [comment]
Changed in #164.
