### ISSUE TITLE
Merge develop into master.

### ISSUE THREAD

**Issue by d4rken** [piwik/piwik-sdk-android#55]
@dotsbb I think we can merge the current develop branch into master.
I've been using it in production for a month now and I'm satisfied.

New people looking to integrate Piwik into their app shouldn't use the build from current master branch.

We could increase the version to 0.0.2 as there were some major changes.

When merging we should also make sure the .jar file is either updated or removed to prevent confusion.

Not sure whats going on with #31

**Comment by dotsbb** [comment]
@d4rken It's nice to hear from you. I'm very grateful for your feedback, really!

For sure, it's good time to merge dev into master. 
I would rather bump dev vesrion to 0.1.0. Current master should be 0.0.2  because it's already ahead  https://github.com/piwik/piwik-sdk-android/tree/v0.0.1 by ~50 commits.

Before we merge it I think it would be nice to have following list done:

* [ ] Fix&close #31 
* [ ] Introduce Change Log
* [ ] Update wiki

I'll try to find some spare time to do it on weekends.

**Comment by d4rken** [comment]
:+1: sounds good.

We could attach the changelog to releases.
i.e.
Read commits between current tag and previous tag, create release for current tag, write changelog into its description.
