### ISSUE TITLE
How can I show returning visitors on Visitor log menu?

### ISSUE THREAD

**Issue by ThanawatMas** [piwik/piwik-sdk-android#58]
On my Piwik server
When I go to menu Visitors -> Visitor log -> visitors
and view data I got a question that it didn't show icon returning user only on Android Device 
![capture2](https://cloud.githubusercontent.com/assets/2458942/9322493/09677dd8-459e-11e5-8c64-735ad98ec225.PNG)
but others always show e.g. iOS, WebBrowser.
![capture](https://cloud.githubusercontent.com/assets/2458942/9322486/05de5736-459e-11e5-91d5-670d1cb267a8.PNG)

P.S. I've tested on my application that always setNewSession on new login

---> In deeply , I found on "Tracker.class"
Line 101: this.visitorId = this.getRandomVisitorId();
Line 590:  private String getRandomVisitorId() {
        return UUID.randomUUID().toString().replaceAll("-", "").substring(0, 16);
    }

**Comment by d4rken** [comment]
Which version of the sdk are you using?
The previous master-branch version was bugged in that regard, see #18 which should have been fixed by #50.

I would suggest to update to the current version of 0.0.2. It is an almost complete rewrite, so you will have to change your code, but many things have been fixed.

**Comment by ThanawatMas** [comment]
I use version 0.0.1 .
For now, I solve this issue follow your suggestion. Thank you very much. @d4rken
