### ISSUE TITLE
Piwik for Android SDK - Battery Usage

### ISSUE THREAD

**Issue by bmorrisidm** [piwik/piwik-sdk-android#91]
Hi there,

As per this thread I am posting here

https://forum.piwik.org/t/piwik-for-android-sdk-battery-usage/18623

We've looked at this a bit more and it looks like Piwik does do dispatching, every 2 minutes we think. However the question still stands regarding battery usage and addressing the points in this article which seems to indicate app tracking is very difficult.

http://www.lunametrics.com/blog/2015/09/24/5-considerations-google-tag-manager-mobile-apps/

Also if it uses dispatching is it impossible to gather all hits or is that a Google Play Services issue and Piwik doesn't use that.

Thanks for any feedback.

**Comment by dotsbb** [comment]
The manual dispatch on minimize/close app seems to be a reasonable solution in this case.
For now I can recommend You to reduce dispatching interval: it shouldn't affect battery usage, but it wouldn't give You 100% tracking accuracy.

**Comment by d4rken** [comment]
The client-side app tracking part is not computationally difficult and unless mistakes were made the impact on batterylife is neglible.

Piwik is more like Google Analytics, not Google Tag Manager.
http://stackoverflow.com/questions/23640645/what-is-the-difference-between-google-tag-manager-and-google-analytics

The impact of a few misses on ccuracy is also minor in larger products due to the volume of hits. The SDK's prevalent reason for missing hits is currently loss of network connectivity (#16).

**Comment by d4rken** [comment]
Seems solved.
